# Generated by Django 5.2.8 on 2025-11-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.IntegerField(unique=True)),
                ("ename", models.CharField(max_length=100)),
            ],
        ),
    ]
