# Generated by Django 5.2.8 on 2025-11-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bangjob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("company", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Bhiharjob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("company", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Punejob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("company", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
